yatube/about/urls.py
from django.urls import path

from . import views
from .apps import AboutConfig

app_name = AboutConfig.name

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views
from .apps import PostsConfig

app_name = PostsConfig.name

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new_post, name='new_post'),
    path('follow/', views.follow_index, name='follow_index'),
    path('<str:username>/', views.profile, name='profile'),
    path(
        '<str:username>/follow/', views.profile_follow, name='profile_follow'
    ),
    path(
        '<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/', views.post_edit, name='post_edit'
    ),
    path('<str:username>/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        '<str:username>/<int:post_id>/comment',
        views.add_comment,
        name='add_comment',
    ),
]

af = collections.Counter()

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import posts.views as posts

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

urlpatterns = [
    path('404/', posts.page_not_found),
    path('500/', posts.server_error),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('group/<slug>/', posts.group_posts, name='group'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

yatube/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        
        {% block title %}
            The Last Social Media You'll Ever Need
        {% endblock %} | Yatube
            
    </title>
    {% load static %}
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>

    {% include 'nav.html' %}
    <main>
        <div class="container">
            <h1>
            {% block header %}
            {% endblock %}
            </h1>
            {% block content %}
            {% endblock %} 
        </div>
    </main>
    {% include 'footer.html' %}

</body>
</html>

yatube/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
  <p class="m-0 text-dark text-center ">
    Социальная сеть <span style="color:red">Ya</span>tube
  </p>
</footer> 

yatube/templates/group.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
    Записи сообщества {{ group.title }}
{% endblock %}

{% block header %}
    {{ group.title }}
{% endblock %}

{% block content %}
    <p>{{ group.description }}</p>
    {% for post in page %}        
        {% include 'posts/post_item.html' with post=post %}
    {% endfor %}
    {% include 'paginator.html' %}
{% endblock %}

yatube/templates/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}

{% block header %}Последние обновления на сайте{% endblock %}

{% block content %}
    {% include "posts/includes/menu.html" with index=True%}
    {% cache 1 index_page page.number%}
    {% for post in page %}    
        {% include "posts/post_item.html" with post=post %}
    {% endfor %}
    {% include "paginator.html"%}
    {% endcache %}
{% endblock %}

yatube/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'posts:index' %}"><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
      Пользователь: {{ user.username }}.
      <a class="p-2 text-dark" href="{% url 'posts:new_post' %}">Новая запись</a>
      <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a>
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav> 

yatube/templates/paginator.html
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo; Предыдущая</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Следующая &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %} 