yatube/about/urls.py
from django.urls import path

from . import views
from .apps import AboutConfig

app_name = AboutConfig.name

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views
from .apps import PostsConfig

app_name = PostsConfig.name

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new_post, name='new_post'),
    path('follow/', views.follow_index, name='follow_index'),
    path('<str:username>/', views.profile, name='profile'),
    path(
        '<str:username>/follow/', views.profile_follow, name='profile_follow'
    ),
    path(
        '<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/', views.post_edit, name='post_edit'
    ),
    path('<str:username>/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        '<str:username>/<int:post_id>/comment',
        views.add_comment,
        name='add_comment',
    ),
]

af = collections.Counter()

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import posts.views as posts

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

urlpatterns = [
    path('404/', posts.page_not_found),
    path('500/', posts.server_error),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('group/<slug>/', posts.group_posts, name='group'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.query_utils import Q

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Адрес')
    description = models.TextField(blank=True, verbose_name='Описание')

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст')
    pub_date = models.DateTimeField('Дата', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='posts',
        blank=True,
        null=True,
    )
    image = models.ImageField(upload_to='posts/', blank=True, null=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments'
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='follower'
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow'
            ),
            models.CheckConstraint(
                check=~Q('user', 'author'), name='user_not_author'
            ),
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from http import HTTPStatus

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def index(request):
    posts_list = Post.objects.all().select_related('author', 'group')
    paginator = Paginator(posts_list, 10)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    return render(request, 'index.html', {'page': page})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    return render(request, 'group.html', {'group': group, 'page': page})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, 10)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    is_following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {'author': author, 'page': page, 'is_following': is_following}
    return render(request, 'posts/profile.html', context)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    comments = post.comments.all()
    form = CommentForm()
    context = {'post': post, 'comments': comments, 'form': form}

    return render(request, 'posts/post.html', context)


@login_required
def new_post(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:index')
    return render(request, 'posts/new_edit_post.html', {'form': form})


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    if post.author != request.user:
        return redirect('posts:post', username, post_id)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post', username, post_id)
    return render(
        request, 'posts/new_edit_post.html', {'form': form, 'post': post}
    )


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=HTTPStatus.NOT_FOUND,
    )


def server_error(request):
    return render(
        request, 'misc/500.html', status=HTTPStatus.INTERNAL_SERVER_ERROR
    )


@login_required
def add_comment(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post', username, post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 10)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    return render(request, 'posts/follow.html', {'page': page})


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    follow = Follow.objects.filter(
        user=request.user, author__username=username
    )
    follow.delete()
    return redirect('posts:profile', username)

@login_required
def post_delete(request, username, post_id):
    if username != request.user.username:
        return redirect('/')
    get_object_or_404(Post, id=post_id).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/includes/author_card.html
<div class="col-md-3 mb-3 mt-1">
  <div class="card">
    <div class="card-body">
      <div class="h2">
        {{ author.get_full_name}}
      </div>
      <div class="h3 text-muted">
        @ {{ author }}
      </div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="h6 text-muted">
          Подписчиков: {{ author.following.count }} <br>
          Подписан: {{ author.follower.count }}
        </div>
      </li>
      <li class="list-group-item">
        <div class="h6 text-muted">
          Записей:{{ author.posts.all.count }}
        </div>
      </li>
    </ul>
  </div>
    <li class="list-group-item">
      <div>
        
          {% if author != request.user %}
            {% if is_following %}
              <a
                class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                Отписаться
              </a>
            {% else %}
              <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button">
                Подписаться
              </a>
            {% endif %}
          {% endif %}
        
      </div>
    </li> 
</div>

yatube/templates/posts/includes/comments.html
{% load user_filters %}
  
{% if user.is_authenticated %}
  <div class="card my-4">
    <form action="{% url 'posts:add_comment' post.author.username post.id %}" method="post">
      {% csrf_token %}
      <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <div class="form-group">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </div>
    </form>
  </div>
{% endif %}

{% for item in comments %}
  <div class="media card mb-4">
    <div class="media-body card-body">
      <h5 class="mt-0">
        <a
          href="{% url 'posts:profile' item.author.username %}"
          name="comment_{{ item.id }}"
        >{{ item.author.username }}</a>
      </h5>
      <p>{{ item.text|linebreaksbr }}</p>
    </div>
  </div>
{% endfor %} 

yatube/templates/posts/includes/menu.html
{% if user.is_authenticated %}
  <div class="row">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %} 