yatube/about/urls.py
from django.urls import path

from . import views
from .apps import AboutConfig

app_name = AboutConfig.name

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views
from .apps import PostsConfig

app_name = PostsConfig.name

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new_post, name='new_post'),
    path('follow/', views.follow_index, name='follow_index'),
    path('<str:username>/', views.profile, name='profile'),
    path(
        '<str:username>/follow/', views.profile_follow, name='profile_follow'
    ),
    path(
        '<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/', views.post_edit, name='post_edit'
    ),
    path('<str:username>/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        '<str:username>/<int:post_id>/comment',
        views.add_comment,
        name='add_comment',
    ),
]

af = collections.Counter()

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import posts.views as posts

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

urlpatterns = [
    path('404/', posts.page_not_found),
    path('500/', posts.server_error),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('group/<slug>/', posts.group_posts, name='group'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.query_utils import Q

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Адрес')
    description = models.TextField(blank=True, verbose_name='Описание')

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст')
    pub_date = models.DateTimeField('Дата', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='posts',
        blank=True,
        null=True,
    )
    image = models.ImageField(upload_to='posts/', blank=True, null=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments'
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='follower'
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow'
            ),
            models.CheckConstraint(
                check=~Q('user', 'author'), name='user_not_author'
            ),
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from http import HTTPStatus

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def index(request):
    posts_list = Post.objects.all().select_related('author', 'group')
    paginator = Paginator(posts_list, 10)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    return render(request, 'index.html', {'page': page})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    return render(request, 'group.html', {'group': group, 'page': page})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, 10)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    is_following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {'author': author, 'page': page, 'is_following': is_following}
    return render(request, 'posts/profile.html', context)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    comments = post.comments.all()
    form = CommentForm()
    context = {'post': post, 'comments': comments, 'form': form}

    return render(request, 'posts/post.html', context)


@login_required
def new_post(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:index')
    return render(request, 'posts/new_edit_post.html', {'form': form})


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    if post.author != request.user:
        return redirect('posts:post', username, post_id)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post', username, post_id)
    return render(
        request, 'posts/new_edit_post.html', {'form': form, 'post': post}
    )


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=HTTPStatus.NOT_FOUND,
    )


def server_error(request):
    return render(
        request, 'misc/500.html', status=HTTPStatus.INTERNAL_SERVER_ERROR
    )


@login_required
def add_comment(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post', username, post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 10)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    return render(request, 'posts/follow.html', {'page': page})


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    follow = Follow.objects.filter(
        user=request.user, author__username=username
    )
    follow.delete()
    return redirect('posts:profile', username)

@login_required
def post_delete(request, username, post_id):
    if username != request.user.username:
        return redirect('/')
    get_object_or_404(Post, id=post_id).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}

{% block header %}Последние обновления на сайте{% endblock %}

{% block content %}
    {% include "posts/includes/menu.html" with follow=True%}
    {% for post in page %}
        {% include "posts/post_item.html" with post=post %}
    {% endfor %}
    {% include "paginator.html" %}

{% endblock %}

yatube/templates/posts/new_edit_post.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
{{ form.instance.id|yesno:"Редактировать запись, Добавить запись" }}
{% endblock %}

{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{{ form.instance.id|yesno:"Редактировать запись, Добавить запись" }}</div>
            <div class="card-body">

                {% for error in form.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
                {% endfor %}

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group row" aria-required={{ field.field.required }}>
                        <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
                            {{ field.label }}
                            {% if field.field.required %}
                            <span class="required">*</span>
                            {% endif %}
                        </label>
                        <div class="col-md-6">
                            {{ field|addclass:"form-control" }}
                            {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                {{ field.help_text|safe }}
                            </small>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ form.instance.id|yesno:"Сохранить, Добавить" }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/posts/post.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост № {{ post.id }}{% endblock %}
{% block content %}

<main role="main" class="container">
  <div class="row">
    {% include 'posts/includes/author_card.html' with author=post.author%}
    <div class="col-md-9">
      {% include 'posts/post_item.html' with post=post hidden=True%}
      {% include 'posts/includes/comments.html' with comments=comments.all %}
    </div>
  </div>
</main>

{% endblock %}

yatube/templates/posts/post_item.html
<div class="card mb-3 mt-1 shadow-sm">
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img" src="{{ im.url }}">
    {% endthumbnail %}
    <div class="card-body">
      <p class="card-text">
        <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
          <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
        </a>
        {{ post.text|linebreaksbr }}
      </p>
      {% if post.group %}
        <a class="card-link muted" href="{% url 'group' post.group.slug %}">
          <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
        </a>
      {% endif %}
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          {% if post.comments.exists %}
            <div>
              Комментариев: {{ post.comments.count }}
            </div>
          {% endif %}
          <div class="{% if hidden %} hidden {% endif %}">
            <a class="btn btn-sm btn-primary" href="{% url 'posts:post' post.author.username post.id %}" role="button">
              Добавить комментарий
            </a>
        </div>
          {% if user == post.author %}
            <a class="btn btn-sm btn-info" href="{% url 'posts:post_edit' post.author.username post.id %}" role="button">
              Редактировать
            </a>
            <a class="btn btn-sm btn-primary" href="{% url 'posts:post_delete' post.author.username post.id %}" role="button">
              Удалить
            </a>
          {% endif %}
        </div>
        <small class="text-muted">{{ post.pub_date|date:'d M Y' }}</small>
      </div>
    </div>
  </div> 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профиль{% endblock %}
{% block content %}

<main role="main" class="container">
    <div class="row">
        {% include 'posts/includes/author_card.html' with author=author %}
        <div class="col-md-9">          
            {% for post in page %}                
            {% include 'posts/post_item.html' with post=post %}
            {% endfor %}
            {% include 'paginator.html' %}            
        </div>
    </div>
</main>

{% endblock %}